case(GLFWKeys::MouseButton1): { return(Keys::MOUSE_BUTTON_1); break; }
case(GLFWKeys::MouseButton2): { return(Keys::MOUSE_BUTTON_2); break; }
case(GLFWKeys::MouseButton3): { return(Keys::MOUSE_BUTTON_3); break; }
case(GLFWKeys::MouseButton4): { return(Keys::MOUSE_BUTTON_4); break; }
case(GLFWKeys::MouseButton5): { return(Keys::MOUSE_BUTTON_5); break; }
case(GLFWKeys::MouseButton6): { return(Keys::MOUSE_BUTTON_6); break; }
case(GLFWKeys::MouseButton7): { return(Keys::MOUSE_BUTTON_7); break; }
case(GLFWKeys::MouseButton8): { return(Keys::MOUSE_BUTTON_8); break; }

case(GLFWKeys::Space): { return(Keys::SPACE); break; }
case(GLFWKeys::Apostrophe): { return(Keys::APOSTROPHE); break; }
case(GLFWKeys::Comma): { return(Keys::COMMA); break; }
case(GLFWKeys::Minus): { return(Keys::MINUS); break; }
case(GLFWKeys::Period): { return(Keys::PERIOD); break; }
case(GLFWKeys::Slash): { return(Keys::SLASH); break; }

case(GLFWKeys::D0): { return(Keys::D0); break; }
case(GLFWKeys::D1): { return(Keys::D1); break; }
case(GLFWKeys::D2): { return(Keys::D2); break; }
case(GLFWKeys::D3): { return(Keys::D3); break; }
case(GLFWKeys::D4): { return(Keys::D4); break; }
case(GLFWKeys::D5): { return(Keys::D5); break; }
case(GLFWKeys::D6): { return(Keys::D6); break; }
case(GLFWKeys::D7): { return(Keys::D7); break; }
case(GLFWKeys::D8): { return(Keys::D8); break; }
case(GLFWKeys::D9): { return(Keys::D9); break; }

case(GLFWKeys::Semicolon): { return(Keys::SEMICOLON); break; }
case(GLFWKeys::Equal): { return(Keys::EQUAL); break; }

case(GLFWKeys::A): { return(Keys::A); break; }
case(GLFWKeys::B): { return(Keys::B); break; }
case(GLFWKeys::C): { return(Keys::C); break; }
case(GLFWKeys::D): { return(Keys::D); break; }
case(GLFWKeys::E): { return(Keys::E); break; }
case(GLFWKeys::F): { return(Keys::F); break; }
case(GLFWKeys::G): { return(Keys::G); break; }
case(GLFWKeys::H): { return(Keys::H); break; }
case(GLFWKeys::I): { return(Keys::I); break; }
case(GLFWKeys::J): { return(Keys::J); break; }
case(GLFWKeys::K): { return(Keys::K); break; }
case(GLFWKeys::L): { return(Keys::L); break; }
case(GLFWKeys::M): { return(Keys::M); break; }
case(GLFWKeys::N): { return(Keys::N); break; }
case(GLFWKeys::O): { return(Keys::O); break; }
case(GLFWKeys::P): { return(Keys::P); break; }
case(GLFWKeys::Q): { return(Keys::Q); break; }
case(GLFWKeys::R): { return(Keys::R); break; }
case(GLFWKeys::S): { return(Keys::S); break; }
case(GLFWKeys::T): { return(Keys::T); break; }
case(GLFWKeys::U): { return(Keys::U); break; }
case(GLFWKeys::V): { return(Keys::V); break; }
case(GLFWKeys::W): { return(Keys::W); break; }
case(GLFWKeys::X): { return(Keys::X); break; }
case(GLFWKeys::Y): { return(Keys::Y); break; }
case(GLFWKeys::Z): { return(Keys::Z); break; }

case(GLFWKeys::LeftBracket): { return(Keys::LEFTBRACKET); break; }
case(GLFWKeys::Backslash): { return(Keys::BACKSLASH); break; }
case(GLFWKeys::RightBracket): { return(Keys::RIGHTBRACKET); break; }
case(GLFWKeys::GraveAccent): { return(Keys::GRAVEACCENT); break; }

case(GLFWKeys::World1): { return(Keys::WORLD1); break; }
case(GLFWKeys::World2): { return(Keys::WORLD2); break; }

case(GLFWKeys::Escape): { return(Keys::ESCAPE); break; }
case(GLFWKeys::Enter): { return(Keys::ENTER); break; }
case(GLFWKeys::Tab): { return(Keys::TAB); break; }
case(GLFWKeys::Backspace): { return(Keys::BACKSPACE); break; }
case(GLFWKeys::Insert): { return(Keys::INSERT); break; }
case(GLFWKeys::Delete): { return(Keys::DEL); break; }
case(GLFWKeys::Right): { return(Keys::RIGHT); break; }
case(GLFWKeys::Left): { return(Keys::LEFT); break; }
case(GLFWKeys::Down): { return(Keys::DOWN); break; }
case(GLFWKeys::Up): { return(Keys::UP); break; }

case(GLFWKeys::PageUp): { return(Keys::PAGEUP); break; }
case(GLFWKeys::PageDown): { return(Keys::PAGEDOWN); break; }
case(GLFWKeys::Home): { return(Keys::HOME); break; }
case(GLFWKeys::End): { return(Keys::END); break; }
case(GLFWKeys::CapsLock): { return(Keys::CAPSLOCK); break; }
case(GLFWKeys::ScrollLock): { return(Keys::SCROLLLOCK); break; }
case(GLFWKeys::NumLock): { return(Keys::NUMLOCK); break; }
case(GLFWKeys::PrintScreen): { return(Keys::PRINTSCREEN); break; }
case(GLFWKeys::Pause): { return(Keys::PAUSE); break; }

case(GLFWKeys::F1): { return(Keys::F1); break; }
case(GLFWKeys::F2): { return(Keys::F2); break; }
case(GLFWKeys::F3): { return(Keys::F3); break; }
case(GLFWKeys::F4): { return(Keys::F4); break; }
case(GLFWKeys::F5): { return(Keys::F5); break; }
case(GLFWKeys::F6): { return(Keys::F6); break; }
case(GLFWKeys::F7): { return(Keys::F7); break; }
case(GLFWKeys::F8): { return(Keys::F8); break; }
case(GLFWKeys::F9): { return(Keys::F9); break; }
case(GLFWKeys::F10): { return(Keys::F10); break; }
case(GLFWKeys::F11): { return(Keys::F11); break; }
case(GLFWKeys::F12): { return(Keys::F12); break; }
case(GLFWKeys::F13): { return(Keys::F13); break; }
case(GLFWKeys::F14): { return(Keys::F14); break; }
case(GLFWKeys::F15): { return(Keys::F15); break; }
case(GLFWKeys::F16): { return(Keys::F16); break; }
case(GLFWKeys::F17): { return(Keys::F17); break; }
case(GLFWKeys::F18): { return(Keys::F18); break; }
case(GLFWKeys::F19): { return(Keys::F19); break; }
case(GLFWKeys::F20): { return(Keys::F20); break; }
case(GLFWKeys::F21): { return(Keys::F21); break; }
case(GLFWKeys::F22): { return(Keys::F22); break; }
case(GLFWKeys::F23): { return(Keys::F23); break; }
case(GLFWKeys::F24): { return(Keys::F24); break; }
case(GLFWKeys::F25): { return(Keys::F25); break; }

case(GLFWKeys::KP0): { return(Keys::KP0); break; }
case(GLFWKeys::KP1): { return(Keys::KP1); break; }
case(GLFWKeys::KP2): { return(Keys::KP2); break; }
case(GLFWKeys::KP3): { return(Keys::KP3); break; }
case(GLFWKeys::KP4): { return(Keys::KP4); break; }
case(GLFWKeys::KP5): { return(Keys::KP5); break; }
case(GLFWKeys::KP6): { return(Keys::KP6); break; }
case(GLFWKeys::KP7): { return(Keys::KP7); break; }
case(GLFWKeys::KP8): { return(Keys::KP8); break; }
case(GLFWKeys::KP9): { return(Keys::KP9); break; }

case(GLFWKeys::KPDecimal): { return(Keys::KPDECIMAL); break; }
case(GLFWKeys::KPDivide): { return(Keys::KPDIVIDE); break; }
case(GLFWKeys::KPMultiply): { return(Keys::KPMULTIPLY); break; }
case(GLFWKeys::KPSubtract): { return(Keys::KPSUBTRACT); break; }
case(GLFWKeys::KPAdd): { return(Keys::KPADD); break; }
case(GLFWKeys::KPEqual): { return(Keys::KPEQUAL); break; }
case(GLFWKeys::KPEnter): { return(Keys::KPENTER); break; }

case(GLFWKeys::LeftShift): { return(Keys::LETSHIFT); break; }
case(GLFWKeys::LeftControl): { return(Keys::LEFTCONTROL); break; }
case(GLFWKeys::LeftAlt): { return(Keys::LEFTALT); break; }
case(GLFWKeys::LeftSuper): { return(Keys::LEFTSUPER); break; }
case(GLFWKeys::RightShift): { return(Keys::RIGHTSHIFT); break; }
case(GLFWKeys::RightControl): { return(Keys::RIGHTCONTROL); break; }
case(GLFWKeys::RightAlt): { return(Keys::RIGHTALT); break; }
case(GLFWKeys::RightSuper): { return(Keys::RIGHTSUPER); break; }

case(GLFWKeys::Menu): { return(Keys::MENU); break; }
