case(Keys::MOUSE_BUTTON_1): { return(GLFWKeys::MouseButton1); break; }
case(Keys::MOUSE_BUTTON_2): { return(GLFWKeys::MouseButton2); break; }
case(Keys::MOUSE_BUTTON_3): { return(GLFWKeys::MouseButton3); break; }
case(Keys::MOUSE_BUTTON_4): { return(GLFWKeys::MouseButton4); break; }
case(Keys::MOUSE_BUTTON_5): { return(GLFWKeys::MouseButton5); break; }
case(Keys::MOUSE_BUTTON_6): { return(GLFWKeys::MouseButton6); break; }
case(Keys::MOUSE_BUTTON_7): { return(GLFWKeys::MouseButton7); break; }
case(Keys::MOUSE_BUTTON_8): { return(GLFWKeys::MouseButton8); break; }

case(Keys::SPACE): { return(GLFWKeys::Space); break; }
case(Keys::APOSTROPHE): { return(GLFWKeys::Apostrophe); break; }
case(Keys::COMMA): { return(GLFWKeys::Comma); break; }
case(Keys::MINUS): { return(GLFWKeys::Minus); break; }
case(Keys::PERIOD): { return(GLFWKeys::Period); break; }
case(Keys::SLASH): { return(GLFWKeys::Slash); break; }

case(Keys::D0): { return(GLFWKeys::D0); break; }
case(Keys::D1): { return(GLFWKeys::D1); break; }
case(Keys::D2): { return(GLFWKeys::D2); break; }
case(Keys::D3): { return(GLFWKeys::D3); break; }
case(Keys::D4): { return(GLFWKeys::D4); break; }
case(Keys::D5): { return(GLFWKeys::D5); break; }
case(Keys::D6): { return(GLFWKeys::D6); break; }
case(Keys::D7): { return(GLFWKeys::D7); break; }
case(Keys::D8): { return(GLFWKeys::D8); break; }
case(Keys::D9): { return(GLFWKeys::D9); break; }

case(Keys::SEMICOLON): { return(GLFWKeys::Semicolon); break; }
case(Keys::EQUAL): { return(GLFWKeys::Equal); break; }

case(Keys::A): { return(GLFWKeys::A); break; }
case(Keys::B): { return(GLFWKeys::B); break; }
case(Keys::C): { return(GLFWKeys::C); break; }
case(Keys::D): { return(GLFWKeys::D); break; }
case(Keys::E): { return(GLFWKeys::E); break; }
case(Keys::F): { return(GLFWKeys::F); break; }
case(Keys::G): { return(GLFWKeys::G); break; }
case(Keys::H): { return(GLFWKeys::H); break; }
case(Keys::I): { return(GLFWKeys::I); break; }
case(Keys::J): { return(GLFWKeys::J); break; }
case(Keys::K): { return(GLFWKeys::K); break; }
case(Keys::L): { return(GLFWKeys::L); break; }
case(Keys::M): { return(GLFWKeys::M); break; }
case(Keys::N): { return(GLFWKeys::N); break; }
case(Keys::O): { return(GLFWKeys::O); break; }
case(Keys::P): { return(GLFWKeys::P); break; }
case(Keys::Q): { return(GLFWKeys::Q); break; }
case(Keys::R): { return(GLFWKeys::R); break; }
case(Keys::S): { return(GLFWKeys::S); break; }
case(Keys::T): { return(GLFWKeys::T); break; }
case(Keys::U): { return(GLFWKeys::U); break; }
case(Keys::V): { return(GLFWKeys::V); break; }
case(Keys::W): { return(GLFWKeys::W); break; }
case(Keys::X): { return(GLFWKeys::X); break; }
case(Keys::Y): { return(GLFWKeys::Y); break; }
case(Keys::Z): { return(GLFWKeys::Z); break; }

case(Keys::LEFTBRACKET): { return(GLFWKeys::LeftBracket); break; }
case(Keys::BACKSLASH): { return(GLFWKeys::Backslash); break; }
case(Keys::RIGHTBRACKET): { return(GLFWKeys::RightBracket); break; }
case(Keys::GRAVEACCENT): { return(GLFWKeys::GraveAccent); break; }

case(Keys::WORLD1): { return(GLFWKeys::World1); break; }
case(Keys::WORLD2): { return(GLFWKeys::World2); break; }

case(Keys::ESCAPE): { return(GLFWKeys::Escape); break; }
case(Keys::ENTER): { return(GLFWKeys::Enter); break; }
case(Keys::TAB): { return(GLFWKeys::Tab); break; }
case(Keys::BACKSPACE): { return(GLFWKeys::Backspace); break; }
case(Keys::INSERT): { return(GLFWKeys::Insert); break; }
case(Keys::DEL): { return(GLFWKeys::Delete); break; }
case(Keys::RIGHT): { return(GLFWKeys::Right); break; }
case(Keys::LEFT): { return(GLFWKeys::Left); break; }
case(Keys::DOWN): { return(GLFWKeys::Down); break; }
case(Keys::UP): { return(GLFWKeys::Up); break; }

case(Keys::PAGEUP): { return(GLFWKeys::PageUp); break; }
case(Keys::PAGEDOWN): { return(GLFWKeys::PageDown); break; }
case(Keys::HOME): { return(GLFWKeys::Home); break; }
case(Keys::END): { return(GLFWKeys::End); break; }
case(Keys::CAPSLOCK): { return(GLFWKeys::CapsLock); break; }
case(Keys::SCROLLLOCK): { return(GLFWKeys::ScrollLock); break; }
case(Keys::NUMLOCK): { return(GLFWKeys::NumLock); break; }
case(Keys::PRINTSCREEN): { return(GLFWKeys::PrintScreen); break; }
case(Keys::PAUSE): { return(GLFWKeys::Pause); break; }

case(Keys::F1): { return(GLFWKeys::F1); break; }
case(Keys::F2): { return(GLFWKeys::F2); break; }
case(Keys::F3): { return(GLFWKeys::F3); break; }
case(Keys::F4): { return(GLFWKeys::F4); break; }
case(Keys::F5): { return(GLFWKeys::F5); break; }
case(Keys::F6): { return(GLFWKeys::F6); break; }
case(Keys::F7): { return(GLFWKeys::F7); break; }
case(Keys::F8): { return(GLFWKeys::F8); break; }
case(Keys::F9): { return(GLFWKeys::F9); break; }
case(Keys::F10): { return(GLFWKeys::F10); break; }
case(Keys::F11): { return(GLFWKeys::F11); break; }
case(Keys::F12): { return(GLFWKeys::F12); break; }
case(Keys::F13): { return(GLFWKeys::F13); break; }
case(Keys::F14): { return(GLFWKeys::F14); break; }
case(Keys::F15): { return(GLFWKeys::F15); break; }
case(Keys::F16): { return(GLFWKeys::F16); break; }
case(Keys::F17): { return(GLFWKeys::F17); break; }
case(Keys::F18): { return(GLFWKeys::F18); break; }
case(Keys::F19): { return(GLFWKeys::F19); break; }
case(Keys::F20): { return(GLFWKeys::F20); break; }
case(Keys::F21): { return(GLFWKeys::F21); break; }
case(Keys::F22): { return(GLFWKeys::F22); break; }
case(Keys::F23): { return(GLFWKeys::F23); break; }
case(Keys::F24): { return(GLFWKeys::F24); break; }
case(Keys::F25): { return(GLFWKeys::F25); break; }

case(Keys::KP0): { return(GLFWKeys::KP0); break; }
case(Keys::KP1): { return(GLFWKeys::KP1); break; }
case(Keys::KP2): { return(GLFWKeys::KP2); break; }
case(Keys::KP3): { return(GLFWKeys::KP3); break; }
case(Keys::KP4): { return(GLFWKeys::KP4); break; }
case(Keys::KP5): { return(GLFWKeys::KP5); break; }
case(Keys::KP6): { return(GLFWKeys::KP6); break; }
case(Keys::KP7): { return(GLFWKeys::KP7); break; }
case(Keys::KP8): { return(GLFWKeys::KP8); break; }
case(Keys::KP9): { return(GLFWKeys::KP9); break; }

case(Keys::KPDECIMAL): { return(GLFWKeys::KPDecimal); break; }
case(Keys::KPDIVIDE): { return(GLFWKeys::KPDivide); break; }
case(Keys::KPMULTIPLY): { return(GLFWKeys::KPMultiply); break; }
case(Keys::KPSUBTRACT): { return(GLFWKeys::KPSubtract); break; }
case(Keys::KPADD): { return(GLFWKeys::KPAdd); break; }
case(Keys::KPEQUAL): { return(GLFWKeys::KPEqual); break; }
case(Keys::KPENTER): { return(GLFWKeys::KPEnter); break; }

case(Keys::LETSHIFT): { return(GLFWKeys::LeftShift); break; }
case(Keys::LEFTCONTROL): { return(GLFWKeys::LeftControl); break; }
case(Keys::LEFTALT): { return(GLFWKeys::LeftAlt); break; }
case(Keys::LEFTSUPER): { return(GLFWKeys::LeftSuper); break; }
case(Keys::RIGHTSHFIT): { return(GLFWKeys::RightShift); break; }
case(Keys::RIGHTCONTROL): { return(GLFWKeys::RightControl); break; }
case(Keys::RIGHTALT): { return(GLFWKeys::RightAlt); break; }
case(Keys::RIGHTSUPER): { return(GLFWKeys::RightSuper); break; }

case(Keys::MENU): { return(GLFWKeys::Menu); break; }